apiVersion : apps/v1
kind: Deployment
metadata:
  name: tsfunctionnodeserver 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsfunctionnodeserver
  template:
    metadata:
      labels:
        app: tsfunctionnodeserver 
    spec:
      containers:
        - name: tsfunctionnodeserver 
          image: acrmingliang001.azurecr.io/mingliangfu123/hello-world-node:9
          ports:
          - containerPort: 80


---
apiVersion: apps/v1
kind: Service
metadata:
  name: tsfunctionnodeserver
spec:
  selector:
    app: tsfunctionnodeserver
  ports:
    - name: tsfunctionnodeserverport
      port: 80
      targetPort: 80
  type: ClusterIP